export const casesListing = [
    {
        title: "Case 1: Tortuous Artery",
        image: require("../../../assets/listing_images/Case1.jpg"),
        tags: "Tortuous, Severely Angulated, LV Assist",
        case: 1,
    },
    {
        title: "Case 2: Ectatic And Severely Tortuous Long ISR of RCA",
        image: require("../../../assets/listing_images/Case2.jpg"),
        tags: "Ectactic, Tortuous, ISR, Guide Extension",
        case: 2,
    },
    {
        title: "Case 3: OCT Guided Complex Intervention Of LM And Long Calcified Aneurysmal LAD",
        image: require("../../../assets/listing_images/Case3.jpg"),
        tags: "Calcified LM, Aneurysmal, Bifurcation, Rota",
        case: 3,
    },
    {
        title: "Case 4: LAD CTO – D1 Bifurcation",
        image: require("../../../assets/listing_images/Case4.jpg"),
        tags: "CTO, Bifurcation, Antegrade, Minicrush",
        case: 4,
    },
    {
        title: "Case 5: Complex Proximal RCA CTO ISR Via Antegrade Approach Followed By Laser Atherectomy And Atherotomy",
        image: require("../../../assets/listing_images/Case5.jpg"),
        tags: "CTO, Antegrade, ISR, Laser",
        case: 5,
    },
    {
        title: "Case 6: Mid RCA CTO via Antegrade Recanalization",
        image: require("../../../assets/listing_images/Case6.jpg"),
        tags: "CTO, Antegrade, Dual Injection",
        case: 6,
    },
    {
        title: "Case 7: Severely Angulated Vein Graft PCI",
        image: require("../../../assets/listing_images/Case7.jpg"),
        tags: "Angulated, Vein Graft, Failed First Attempt",
        case: 7,
    },
    {
        title: "Case 8: Aneurysmal RCA Disease",
        image: require("../../../assets/listing_images/Case8.jpg"),
        tags: "Aneurysmal, Angulated, CABG",
        case: 8,
    },
    {
        title: "Case 9: Protected PCI of complex calcified LAD using OA and DES with Impella LV assist",
        image: require("../../../assets/listing_images/Case9.jpg"),
        tags: "Calcified, Orbital, LV Assist",
        case: 9,
    },
    {
        title: "Case 10: RCA CTO (Antegrade Approach)",
        image: require("../../../assets/listing_images/Case10.jpg"),
        tags: "CTO, Antegrade, Guide Extension",
        case: 10,
    },
    {
        title: "Case 11: Thrombotic Lesion (STEMI)",
        image: require("../../../assets/listing_images/Case11.jpg"),
        tags: "STEMI, Thrombotic, New Onset Angina",
        case: 11,
    },
    {
        title: "Case 12: CTO Ostial LAD (Retrograde / Antegrade)",
        image: require("../../../assets/listing_images/Case12.jpg"),
        tags: "CTO, Ostial LAD, Antegrade, Retrograde",
        case: 12,
    },
    {
        title: "Case 13: Calcified Prox LAD and Angulated Diagonal Bifurcation Intervention",
        image: require("../../../assets/listing_images/Case13.jpg"),
        tags: "Calcified, Angulated, Bifurcation, Angulated Catheters",
        case: 13,
    },
    {
        title: "Case 14: RCA CTO via Antegrade Approach",
        image: require("../../../assets/listing_images/Case14.jpg"),
        tags: "CTO, Antegrade, CenterCross Device",
        case: 14,
    },
    {
        title: "Case 15: Rotational Atherectomy and DES of CTO RCA BMS ISR",
        image: require("../../../assets/listing_images/Case15.jpg"),
        tags: "CTO, ISR, Rota, Rotawire ES",
        case: 15,
    },
    {
        title: "Case 16: PCI of Distal RCA CTO by Retrograde Recanalization using LAD-Septal Collaterals",
        image: require("../../../assets/listing_images/Case16.jpg"),
        tags: "CTO, Retrograde, Septal Surfing",
        case: 16,
    },
    {
        title: "Case 17: CTO Retrograde",
        image: require("../../../assets/listing_images/Case17.jpg"),
        tags: "CTO, Retrograde, Septal Surfing",
        case: 17,
    },
    {
        title: "Case 18: CTO Retrograde",
        image: require("../../../assets/listing_images/Case18.jpg"),
        tags: "Retrograde",
        case: 18,
    },
    {
        title: "Case 19: Revascularization of Calcific LM Bifurcation and Aneurysmal pLAD",
        image: require("../../../assets/listing_images/Case19.jpg"),
        tags: "Calcified, LM, Bifurcation, Aneurysmal",
        case: 19,
    },
    {
        title: "Case 20: Complex Multivessel PCI in a High SYNTAX Score",
        image: require("../../../assets/listing_images/Case20.jpg"),
        tags: "Calcified, Subtotal Occlusion, Rota",
        case: 20,
    },
    {
        title: "Case 21: RCA CTO PCI with Antegrade Approach",
        image: require("../../../assets/listing_images/Case21.jpg"),
        tags: "CTO, Antegrade",
        case: 21,
    },
    {
        title: "Case 22: Extremely Tortuous Angulated mid LAD Diagonal Bifurcation Lesion",
        image: require("../../../assets/listing_images/Case22.jpg"),
        tags: "Tortuous, Angulated, Bifurcation, Angulated Catheters",
        case: 22,
    },
    {
        title: "Case 23: Simple Lesion",
        image: require("../../../assets/listing_images/Case23.jpg"),
        tags: "Simple Lesion, Ramus",
        case: 23,
    },
    {
        title: "Case 24: Complex PCI of Tortuous Calcified RCA Using Rota With Guide Extension Support",
        image: require("../../../assets/listing_images/Case24.jpg"),
        tags: "Calcified, Tortuous, Wire Bias, Rota",
        case: 24,
    },
    {
        title: "Case 25: Angulated LAD Intervention Using Angulated Catheter",
        image: require("../../../assets/listing_images/Case25.jpg"),
        tags: "Angulated, Calcified, Bifurcation, Provisional",
        case: 25,
    },
    {
        title: "Case 26: Severely Angulated and Tortuous RCA Intervention",
        image: require("../../../assets/listing_images/Case26.jpg"),
        tags: "Angulated, Calcified, Bifurcation, Provisional",
        case: 26,
    }
];
