export const wires = [
    {
        id: 1,
        "link_item": "Runthrough",
        "model": "Runthrough NS Floppy/NS Extra Floppy",
        "image_url": require("../../../../assets/library_images/Terumo-1-Runthrough-NS-Floppy.png"),
        "copyright_notice": "Image provided courtesy of Terumo Interventional Systems. © 2021 Terumo Interventional Systems or its affiliates. All rights reserved.",
        "manufacturer": "Terumo Interventional Systems",
        "core_material": "Duo Core – Stainless steel proximal shaft + nitinol distal tip (hybrid core)",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic with distal 2mm Hydrophobic silicone coating",
        "tip_load": "1g / 0.6g",
        "radiopaque_length": "3cm",
        "available_lengths": "180cm / 180, 300cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Workhorse wire"
    },
    {
        id: 2,
        "link_item": "Balance Middleweight",
        "model": "BMW",
        "image_url": require("../../../../assets/library_images/Abbott-1-BMW.png"),
        "copyright_notice": "Image provided courtesy of Abbott. © 2021 Abbott or its affiliates. All rights reserved.",
        "manufacturer": "Abbott",
        "core_material": "Elastinite Nitinol",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Shaping ribbon",
        "tip_coating": "Hydrophilic or Hydrophobic",
        "tip_load": "0.6g",
        "radiopaque_length": "3cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Straight, J-tip",
        "preferred_uses": "Workhorse wire"
    },
    {
        id: 3,
        "link_item": "Sion Blue",
        "model": "Sion Blue",
        "image_url": require("../../../../assets/library_images/Asahi-2-SION-blue.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core [round core + twist wire]",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating (18.5cm) with distal hydrophobic silicone coating (1.5cm) [Hybrid Coating)",
        "tip_load": "0.5g",
        "radiopaque_length": "3cm",
        "available_lengths": "180cm, 300cm",
        "available_tip_styles": "Straight, J-tip",
        "preferred_uses": "Workhorse wire, all around wire"
    },
    {
        id: 4,
        "link_item": "Fielder",
        "model": "Fielder/Fielder FC",
        "image_url": require("../../../../assets/library_images/Asahi-12-FIELDER.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating over polymer jacket (20 cm)",
        "tip_load": "1g / 0.8g",
        "radiopaque_length": "3cm",
        "available_lengths": "180cm, 300cm",
        "available_tip_styles": "Straight, J-tip",
        "preferred_uses": "Frontline finesse, Tortuous vessels, Side branch access"
    },
    {
        id: 5,
        "link_item": "Whisper",
        "model": "Whisper MS",
        "image_url": require("../../../../assets/library_images/Abbott-13-Whisper-MS.png"),
        "copyright_notice": "Image provided courtesy of Abbott. © 2021 Abbott or its affiliates. All rights reserved.",
        "manufacturer": "Abbott",
        "core_material": "DURASTEEL",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip [Parabolic Core Grind]",
        "tip_coating": "Full Polymer cover with Hydrophilic coating",
        "tip_load": "1g",
        "radiopaque_length": "3cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Straight, J-tip",
        "preferred_uses": "Frontline finesse, Tortuous vessels, Side branch access"
    },
    {
        id: 6,
        "link_item": "Pilot 50",
        "model": "Pilot 50",
        "image_url": require("../../../../assets/library_images/Abbott-15-Pilot-50.png"),
        "copyright_notice": "Image provided courtesy of Abbott. © 2021 Abbott or its affiliates. All rights reserved.",
        "manufacturer": "Abbott",
        "core_material": "DURASTEEL",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip [Parabolic Core Grind]",
        "tip_coating": "Full Polymer cover with Hydrophilic coating",
        "tip_load": "1.5g",
        "radiopaque_length": "3cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Straight, J-tip",
        "preferred_uses": "Specialty CTO Antegrade"
    },
    {
        id: 7,
        "link_item": "CHOICE Floppy",
        "model": "Cboice Floppy",
        "image_url": require("../../../../assets/library_images/Boston-Scientific-1-Choice-Floppy.png"),
        "copyright_notice": "Image provided courtesy of Boston Scientific. © 2021 Boston Scientific Corporation or its affiliates. All rights reserved.",
        "manufacturer": "Boston Scientific",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating ICE [Polymer Sleeve, distal 3cm uncoated]",
        "tip_load": "0.75g",
        "radiopaque_length": "3cm",
        "available_lengths": "182, 300cm",
        "available_tip_styles": "Straight, J-shaped",
        "preferred_uses": "Workhorse wire"
    },
    {
        id: 8,
        "link_item": "Runthrough",
        "model": "Runthrough NS Floppy/NS Extra Floppy",
        "image_url": require("../../../../assets/library_images/Terumo-1-Runthrough-NS-Floppy.png"),
        "copyright_notice": "Image provided courtesy of Terumo Interventional Systems. © 2021 Terumo Interventional Systems or its affiliates. All rights reserved.",
        "manufacturer": "Terumo Interventional Systems",
        "core_material": "Duo Core – Stainless steel proximal shaft + nitinol distal tip (hybrid core)",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic with distal 2mm Hydrophobic silicone coating",
        "tip_load": "1g / 0.6g",
        "radiopaque_length": "3cm",
        "available_lengths": "180cm / 180, 300cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Workhorse wire"
    },
    {
        id: 9,
        "link_item": "Fielder",
        "model": "Fielder/Fielder FC",
        "image_url": require("../../../../assets/library_images/Asahi-12-FIELDER.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating over polymer jacket (20 cm)",
        "tip_load": "1g / 0.8g",
        "radiopaque_length": "3cm",
        "available_lengths": "180cm, 300cm",
        "available_tip_styles": "Straight, J-tip",
        "preferred_uses": "Frontline finesse, Tortuous vessels, Side branch access"
    },
    {
        id: 10,
        "link_item": "Whisper",
        "model": "Whisper MS",
        "image_url": require("../../../../assets/library_images/Abbott-13-Whisper-MS.png"),
        "copyright_notice": "Image provided courtesy of Abbott. © 2021 Abbott or its affiliates. All rights reserved.",
        "manufacturer": "Abbott",
        "core_material": "DURASTEEL",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip [Parabolic Core Grind]",
        "tip_coating": "Full Polymer cover with Hydrophilic coating",
        "tip_load": "1g",
        "radiopaque_length": "3cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Straight, J-tip",
        "preferred_uses": "Frontline finesse, Tortuous vessels, Side branch access"
    },
    {
        id: 11,
        "link_item": "Pilot 50",
        "model": "Pilot 50",
        "image_url": require("../../../../assets/library_images/Abbott-15-Pilot-50.png"),
        "copyright_notice": "Image provided courtesy of Abbott. © 2021 Abbott or its affiliates. All rights reserved.",
        "manufacturer": "Abbott",
        "core_material": "DURASTEEL",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip [Parabolic Core Grind]",
        "tip_coating": "Full Polymer cover with Hydrophilic coating",
        "tip_load": "1.5g",
        "radiopaque_length": "3cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Straight, J-tip",
        "preferred_uses": "Specialty CTO Antegrade"
    },
    {
        id: 12,
        "link_item": "Iron Man",
        "model": "Iron Man",
        "image_url": require("../../../../assets/library_images/Abbott-20-Iron-Man.png"),
        "copyright_notice": "Image provided courtesy of Abbott. © 2021 Abbott or its affiliates. All rights reserved.",
        "manufacturer": "Abbott",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophobic",
        "tip_load": "1g",
        "radiopaque_length": "3cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Straight, J-tip",
        "preferred_uses": "Extra Support"
    },
    {
        id: 13,
        "link_item": "Mailman",
        "model": "Mailman",
        "image_url": require("../../../../assets/library_images/Boston-Scientific-14-MAILMAN.png"),
        "copyright_notice": "Image provided courtesy of Boston Scientific. © 2021 Boston Scientific Corporation or its affiliates. All rights reserved.",
        "manufacturer": "Boston Scientific",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic; distal 3cm spring coils uncoated",
        "tip_load": "0.8g",
        "radiopaque_length": "3cm",
        "available_lengths": "180, 300cm",
        "available_tip_styles": "Straight, J-shaped",
        "preferred_uses": "Extra Support"
    },
    {
        id: 14,
        "link_item": "Hi-Torque Balance HeavyWeight",
        "model": "Hi-Torque Balance HeavyWeight",
        "image_url": require("../../../../assets/library_images/Abbott-21-Hi-Torque-Balance-Heavyweight.png"),
        "copyright_notice": "Image provided courtesy of Abbott. © 2021 Abbott or its affiliates. All rights reserved.",
        "manufacturer": "Abbott",
        "core_material": "ELASTINITE Nitinol",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Shaping ribbon",
        "tip_coating": "Hydrophilic",
        "tip_load": "0.8g",
        "radiopaque_length": "4.5cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Straight, J-tip",
        "preferred_uses": "Extra Support"
    },
    {
        id: 15,
        "link_item": "Hi-Torque All-Star",
        "model": "All Star",
        "image_url": require("../../../../assets/library_images/Abbott-19-All-Star.png"),
        "copyright_notice": "Image provided courtesy of Abbott. © 2021 Abbott or its affiliates. All rights reserved.",
        "manufacturer": "Abbott",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "Polymer cover excluding distal tip which is hydrophobic",
        "tip_load": "0.8g",
        "radiopaque_length": "3cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Straight, J-tip",
        "preferred_uses": "Extra Support"
    },
    {
        id: 16,
        "link_item": "CHOICE Extra Support",
        "model": "CHOICE Extra Support",
        "image_url": require("../../../../assets/library_images/Boston-Scientific-12-CHOICE-Extra-Support.png"),
        "copyright_notice": "Image provided courtesy of Boston Scientific. © 2021 Boston Scientific Corporation or its affiliates. All rights reserved.",
        "manufacturer": "Boston Scientific",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic; distal 3cm spring coils uncoated",
        "tip_load": "0.9g",
        "radiopaque_length": "3cm",
        "available_lengths": "182, 300cm",
        "available_tip_styles": "Straight, J-shaped",
        "preferred_uses": "Extra Support"
    },
    {
        id: 17,
        "link_item": "Runthrough",
        "model": "Runthrough NS Floppy/NS Extra Floppy",
        "image_url": require("../../../../assets/library_images/Terumo-1-Runthrough-NS-Floppy.png"),
        "copyright_notice": "Image provided courtesy of Terumo Interventional Systems. © 2021 Terumo Interventional Systems or its affiliates. All rights reserved.",
        "manufacturer": "Terumo Interventional Systems",
        "core_material": "Duo Core – Stainless steel proximal shaft + nitinol distal tip (hybrid core)",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic with distal 2mm Hydrophobic silicone coating",
        "tip_load": "1g / 0.6g",
        "radiopaque_length": "3cm",
        "available_lengths": "180cm / 180, 300cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Workhorse wire"
    },
    {
        id: 18,
        "link_item": "BMW",
        "model": "BMW",
        "image_url": require("../../../../assets/library_images/Abbott-1-BMW.png"),
        "copyright_notice": "Image provided courtesy of Abbott. © 2021 Abbott or its affiliates. All rights reserved.",
        "manufacturer": "Abbott",
        "core_material": "Elastinite Nitinol",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Shaping ribbon",
        "tip_coating": "Hydrophilic or Hydrophobic",
        "tip_load": "0.6g",
        "radiopaque_length": "3cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Straight, J-tip",
        "preferred_uses": "Workhorse wire"
    },
    {
        id: 19,
        "link_item": "CHOICE Floppy",
        "model": "Cboice Floppy",
        "image_url": require("../../../../assets/library_images/Boston-Scientific-1-Choice-Floppy.png"),
        "copyright_notice": "Image provided courtesy of Boston Scientific. © 2021 Boston Scientific Corporation or its affiliates. All rights reserved.",
        "manufacturer": "Boston Scientific",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating ICE [Polymer Sleeve, distal 3cm uncoated]",
        "tip_load": "0.75g",
        "radiopaque_length": "3cm",
        "available_lengths": "182, 300cm",
        "available_tip_styles": "Straight, J-shaped",
        "preferred_uses": "Workhorse wire"
    },
    {
        id: 20,
        "link_item": "Fielder",
        "model": "Fielder/Fielder FC",
        "image_url": require("../../../../assets/library_images/Asahi-12-FIELDER.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating over polymer jacket (20 cm)",
        "tip_load": "1g / 0.8g",
        "radiopaque_length": "3cm",
        "available_lengths": "180, 300cm",
        "available_tip_styles": "Straight, J-tip",
        "preferred_uses": "Frontline finesse, Tortuous vessels, Side branch access"
    },
    {
        id: 21,
        "link_item": "Whisper",
        "model": "Whisper MS",
        "image_url": require("../../../../assets/library_images/Abbott-13-Whisper-MS.png"),
        "copyright_notice": "Image provided courtesy of Abbott. © 2021 Abbott or its affiliates. All rights reserved.",
        "manufacturer": "Abbott",
        "core_material": "DURASTEEL",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip [Parabolic Core Grind]",
        "tip_coating": "Full Polymer cover with Hydrophilic coating",
        "tip_load": "1g",
        "radiopaque_length": "3cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Straight, J-tip",
        "preferred_uses": "Frontline finesse, Tortuous vessels, Side branch access"
    },
    {
        id: 22,
        "link_item": "Pilot 50",
        "model": "Pilot 50",
        "image_url": require("../../../../assets/library_images/Abbott-15-Pilot-50.png"),
        "copyright_notice": "Image provided courtesy of Abbott. © 2021 Abbott or its affiliates. All rights reserved.",
        "manufacturer": "Abbott",
        "core_material": "DURASTEEL",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip [Parabolic Core Grind]",
        "tip_coating": "Full Polymer cover with Hydrophilic coating",
        "tip_load": "1.5g",
        "radiopaque_length": "3cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Straight, J-tip",
        "preferred_uses": "Specialty CTO Antegrade"
    },
    {
        id: 23,
        "link_item": "Gaia 2",
        "model": "Gaia Second",
        "image_url": require("../../../../assets/library_images/Asahi-8-Gaia-Second.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core [round core + twist wire]",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.011\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating 40cm with uncoated distal tip",
        "tip_load": "3.5g, tapered micro-cone",
        "radiopaque_length": "15cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Mini pre-shaped [1mm only]",
        "preferred_uses": "Specialty CTO Antegrade [hard tissue and fibrous caps]"
    },
    {
        id: 24,
        "link_item": "MiracleBros 3",
        "model": "Miraclebros 3",
        "image_url": require("../../../../assets/library_images/Asahi-28-MIRACLEbros-3.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "11cm hydrophobic coating",
        "tip_load": "3g",
        "radiopaque_length": "11cm",
        "available_lengths": "180, 300cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Specialty CTO Antegrade [controlled CTO drilling]"
    },
    {
        id: 25,
        "link_item": "Fielder",
        "model": "Fielder/Fielder FC",
        "image_url": require("../../../../assets/library_images/Asahi-12-FIELDER.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating over polymer jacket (20 cm)",
        "tip_load": "1g / 0.8g",
        "radiopaque_length": "3cm",
        "available_lengths": "180cm, 300cm",
        "available_tip_styles": "Straight, J-tip",
        "preferred_uses": "Frontline finesse, Tortuous vessels, Side branch access"
    },
    {
        id: 26,
        "link_item": "Gaia Series",
        "model": "Gaia First / Second / Third",
        "image_url": require("../../../../assets/library_images/Asahi-6-Gaia-First.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core [round core + twist wire]",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.010\" / 0.011\" / 0.012\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating 40cm with uncoated distal tip",
        "tip_load": "1.7g / 3.5g / 4.5g, tapered micro-cone",
        "radiopaque_length": "15cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Mini pre-shaped [1mm only]",
        "preferred_uses": "Specialty CTO Antegrade"
    },
    {
        id: 27,
        "link_item": "MiracleBros 3",
        "model": "Miraclebros 3",
        "image_url": require("../../../../assets/library_images/Asahi-28-MIRACLEbros-3.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "11cm hydrophobic coating",
        "tip_load": "3g",
        "radiopaque_length": "11cm",
        "available_lengths": "180, 300cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Specialty CTO Antegrade [controlled CTO drilling]"
    },
    {
        id: 28,
        "link_item": "Fielder",
        "model": "Fielder/Fielder FC",
        "image_url": require("../../../../assets/library_images/Asahi-12-FIELDER.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating over polymer jacket (20 cm)",
        "tip_load": "1g / 0.8g",
        "radiopaque_length": "3cm",
        "available_lengths": "180cm, 300cm",
        "available_tip_styles": "Straight, J-tip",
        "preferred_uses": "Frontline finesse, Tortuous vessels, Side branch access"
    },
    {
        id: 29,
        "link_item": "Whisper",
        "model": "Whisper MS",
        "image_url": require("../../../../assets/library_images/Abbott-13-Whisper-MS.png"),
        "copyright_notice": "Image provided courtesy of Abbott. © 2021 Abbott or its affiliates. All rights reserved.",
        "manufacturer": "Abbott",
        "core_material": "DURASTEEL",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip [Parabolic Core Grind]",
        "tip_coating": "Full Polymer cover with Hydrophilic coating",
        "tip_load": "1g",
        "radiopaque_length": "3cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Straight, J-tip",
        "preferred_uses": "Frontline finesse, Tortuous vessels, Side branch access"
    },
    {
        id: 30,
        "link_item": "Pilot 50",
        "model": "Pilot 50",
        "image_url": require("../../../../assets/library_images/Abbott-15-Pilot-50.png"),
        "copyright_notice": "Image provided courtesy of Abbott. © 2021 Abbott or its affiliates. All rights reserved.",
        "manufacturer": "Abbott",
        "core_material": "DURASTEEL",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip [Parabolic Core Grind]",
        "tip_coating": "Full Polymer cover with Hydrophilic coating",
        "tip_load": "1.5g",
        "radiopaque_length": "3cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Straight, J-tip",
        "preferred_uses": "Specialty CTO Antegrade"
    },
    {
        id: 31,
        "link_item": "MiracleBros",
        "model": "Miraclebros 3 / 4.5 / 6 / 12",
        "image_url": require("../../../../assets/library_images/Asahi-28-MIRACLEbros-3.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "11cm hydrophobic coating",
        "tip_load": "3g / 4.5g / 6g / 12g",
        "radiopaque_length": "11cm",
        "available_lengths": "180, 300cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Specialty CTO Antegrade [controlled CTO drilling]"
    },
    {
        id: 32,
        "link_item": "Provia",
        "model": "Provia 3",
        "image_url": require("../../../../assets/library_images/Medtronic-4-PROVIA-3.png"),
        "copyright_notice": "Image provided courtesy of Medtronic. © 2021 Medtronic or its affiliates. All rights reserved.",
        "manufacturer": "Medtronic",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic with 1-mm uncoated tip or Hydrophobic",
        "tip_load": "3g",
        "radiopaque_length": "3cm",
        "available_lengths": "180, 300cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Specialty CTO Antegrade"
    },
    {
        id: 33,
        "link_item": "Angulated microcatheter",
        "model": "Only make these links if you can display the collection of all angulated microcatheters within the app similar to this on the website: https://cardiologyapps.com/guidewireaid/angulated-microcatheters/"
    },
    {
        id: 34,
        "link_item": "Dual lumen catheter",
        "model": "Only make these links if you can display the collection of all dual lumen catheters within the app similar to this on the website: https://cardiologyapps.com/guidewireaid/dual-lumen-catheters/"
    }
];

export const wireCharacteristics = [
    {
        "link_item": "BMW",
        "model": "BMW",
        "image_url": require("../../../../assets/library_images/Abbott-1-BMW.png"),
        "copyright_notice": "Image provided courtesy of Abbott. © 2021 Abbott or its affiliates. All rights reserved.",
        "manufacturer": "Abbott",
        "core_material": "Elastinite Nitinol",
        "core_tapering": "No",
        "diameter": "0.014”",
        "tip_design": "Shaping ribbon",
        "tip_coating": "Hydrophilic or Hydrophobic",
        "tip_load": "0.6g",
        "radiopaque_length": "3cm",
        "available_lengths": "190, 300cm",
        "preferred_uses": "Workhorse wire",
        "available_tip_styles": "190, 300cm",
        "id": 1
    },
    {
        "link_item": "Cougar",
        "model": "Cougar LS / XT",
        "image_url": require("../../../../assets/library_images/Medtronic-1-Cougar-LS-1.png"),
        "copyright_notice": "Image provided courtesy of Medtronic. © 2021 Medtronic or its affiliates. All rights reserved.",
        "manufacturer": "Medtronic",
        "core_material": "Nitinol",
        "core_tapering": "No",
        "diameter": "0.014”",
        "tip_design": "Shaping ribbon",
        "tip_coating": "Hydrophilic or Hydrophobic",
        "tip_load": "NA",
        "radiopaque_length": "3cm",
        "available_lengths": "190, 300cm",
        "preferred_uses": "Workhorse wire",
        "available_tip_styles": "Straight, J-tip",
        "id": 2
    },
    {
        "link_item": "Hi-Torque Floppy",
        "model": "HT Floppy II",
        "image_url": require("../../../../assets/library_images/Abbott-11-HT-Floppy-II.png"),
        "copyright_notice": "Image provided courtesy of Abbott. © 2021 Abbott or its affiliates. All rights reserved.",
        "manufacturer": "Abbott",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Shaping ribbon",
        "tip_coating": "Hydrophilic or Hydrophobic",
        "tip_load": "0.4g",
        "radiopaque_length": "2cm",
        "available_lengths": "190, 300cm",
        "preferred_uses": "Workhorse wire",
        "available_tip_styles": "Straight, J-tip",
        "id": "3"
    },
    {
        "link_item": "High-Torque Turntrac",
        "model": "Turntrac / Turntrac Flex",
        "image_url": require("../../../../assets/library_images/Abbott-5-TURNTRAC.png"),
        "copyright_notice": "Image provided courtesy of Abbott. © 2021 Abbott or its affiliates. All rights reserved.",
        "manufacturer": "Abbott",
        "core_material": "Elastinite Nitinol",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip [Parabolic Core Grind]",
        "tip_coating": "Hydrophilic",
        "tip_load": "0.8g / 0.6g",
        "radiopaque_length": "3cm",
        "available_lengths": "190, 300cm",
        "preferred_uses": "Workhorse wire",
        "available_tip_styles": "Straight",
        "id": "4"
    },
    {
        "link_item": "Versaturn",
        "model": "Versaturn",
        "image_url": require("../../../../assets/library_images/Abbott-7-Versaturn.png"),
        "copyright_notice": "Image provided courtesy of Abbott. © 2021 Abbott or its affiliates. All rights reserved.",
        "manufacturer": "Abbott",
        "core_material": "Elastinite Nitinol",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip [Parabolic Core Grind]",
        "tip_coating": "Hydrophilic",
        "tip_load": "0.8g",
        "radiopaque_length": "3cm",
        "available_lengths": "190cm",
        "preferred_uses": "Workhorse wire",
        "available_tip_styles": "Straight, J-tip",
        "id": "5"
    },
    {
        "link_item": "Runthrough NS",
        "model": "Runthrough NS Floppy/NS Extra Floppy",
        "image_url": require("../../../../assets/library_images/Terumo-1-Runthrough-NS-Floppy.png"),
        "copyright_notice": "Image provided courtesy of Terumo Interventional Systems. © 2021 Terumo Interventional Systems or its affiliates. All rights reserved.",
        "manufacturer": "Terumo Interventional Systems",
        "core_material": "Duo Core – Stainless steel proximal shaft + nitinol distal tip (hybrid core)",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic with distal 2mm Hydrophobic silicone coating",
        "tip_load": "0.5g",
        "radiopaque_length": "3cm",
        "available_lengths": "180cm / 180, 300cm",
        "preferred_uses": "Workhorse wire",
        "available_tip_styles": "Straight",
        "id": "6"
    },
    {
        "link_item": "Samurai RC",
        "model": "Samurai",
        "image_url": require("../../../../assets/library_images/Boston-Scientific-16-SAMURAI.png"),
        "copyright_notice": "Image provided courtesy of Boston Scientific. © 2021 Boston Scientific or its affiliates. All rights reserved.",
        "manufacturer": "Boston Scientific",
        "core_material": "Stainless Steel [Inner core technology]",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip with inner coil technology",
        "tip_coating": "Hydrophilic, distal 1 cm reduced hydrophilic coating",
        "tip_load": "0.5g",
        "radiopaque_length": "4cm",
        "available_lengths": "190, 300cm",
        "preferred_uses": "Workhorse wire",
        "available_tip_styles": "Straight, J-tip",
        "id": "7"
    },
    {
        "link_item": "Sion Blue",
        "model": "Sion Blue",
        "image_url": require("../../../../assets/library_images/Asahi-2-SION-blue.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core [round core + twist wire]",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating (18.5cm) with distal hydrophobic silicone coating (1.5cm) [Hybrid Coating)",
        "tip_load": "0.5g",
        "radiopaque_length": "3cm",
        "available_lengths": "180cm, 300cm",
        "preferred_uses": "Workhorse wire, all around wire",
        "available_tip_styles": "Straight, J-tip",
        "id": "8"
    },
    {
        "link_item": "CHOICE Extra Support",
        "model": "CHOICE Extra Support",
        "image_url": require("../../../../assets/library_images/Boston-Scientific-12-CHOICE-Extra-Support.png"),
        "copyright_notice": "Image provided courtesy of Boston Scientific. © 2021 Boston Scientific Corporation or its affiliates. All rights reserved.",
        "manufacturer": "Boston Scientific",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic; distal 3cm spring coils uncoated",
        "tip_load": "0.9g",
        "radiopaque_length": "3cm",
        "available_lengths": "182, 300cm",
        "preferred_uses": "Extra Support",
        "available_tip_styles": "Straight, J-shaped",
        "id": "9"
    },
    {
        "link_item": "Grand Slam",
        "model": "Grand Slam",
        "image_url": require("../../../../assets/library_images/Asahi-26-GRAND-SLAM.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophobic",
        "tip_load": "0.7g",
        "radiopaque_length": "4cm",
        "available_lengths": "180, 300cm",
        "preferred_uses": "Extra support [highest support of frontline Asahi wires]",
        "available_tip_styles": "Straight, J-tip",
        "id": "10"
    },
    {
        "link_item": "Hi-Torque All-Star",
        "model": "All Star",
        "image_url": require("../../../../assets/library_images/Abbott-19-All-Star.png"),
        "copyright_notice": "Image provided courtesy of Abbott. © 2021 Abbott or its affiliates. All rights reserved.",
        "manufacturer": "Abbott",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "Polymer cover excluding distal tip which is hydrophobic",
        "tip_load": "0.8g",
        "radiopaque_length": "3cm",
        "available_lengths": "190, 300cm",
        "preferred_uses": "Extra Support",
        "available_tip_styles": "Straight, J-tip",
        "id": "11"
    },
    {
        "link_item": "Hi-Torque Balance Heavyweight",
        "model": "Hi-Torque Balance HeavyWeight",
        "image_url": require("../../../../assets/library_images/Abbott-21-Hi-Torque-Balance-Heavyweight.png"),
        "copyright_notice": "Image provided courtesy of Abbott. © 2021 Abbott or its affiliates. All rights reserved.",
        "manufacturer": "Abbott",
        "core_material": "ELASTINITE Nitinol",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Shaping ribbon",
        "tip_coating": "Hydrophilic",
        "tip_load": "0.8g",
        "radiopaque_length": "4.5cm",
        "available_lengths": "190, 300cm",
        "preferred_uses": "Extra Support",
        "available_tip_styles": "Straight, J-tip",
        "id": "12"
    },
    {
        "link_item": "Hi-Torque Ironman",
        "model": "Iron Man",
        "image_url": require("../../../../assets/library_images/Abbott-20-Iron-Man.png"),
        "copyright_notice": "Image provided courtesy of Abbott. © 2021 Abbott or its affiliates. All rights reserved.",
        "manufacturer": "Abbott",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophobic",
        "tip_load": "1g",
        "radiopaque_length": "3cm",
        "available_lengths": "190, 300cm",
        "preferred_uses": "Extra Support",
        "available_tip_styles": "Straight, J-tip",
        "id": "13"
    },
    {
        "link_item": "Mailman",
        "model": "Mailman",
        "image_url": require("../../../../assets/library_images/Boston-Scientific-14-MAILMAN.png"),
        "copyright_notice": "Image provided courtesy of Boston Scientific. © 2021 Boston Scientific Corporation or its affiliates. All rights reserved.",
        "manufacturer": "Boston Scientific",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic; distal 3cm spring coils uncoated",
        "tip_load": "0.8g",
        "radiopaque_length": "3cm",
        "available_lengths": "180, 300cm",
        "preferred_uses": "Extra Support",
        "available_tip_styles": "Straight, J-shaped",
        "id": "14"
    },
    {
        "link_item": "Bandit",
        "model": "Bandit",
        "image_url": require("../../../../assets/library_images/Teleflex-3-BANDIT.png"),
        "copyright_notice": "Image provided courtesy of Teleflex. © 2021 Teleflex or its affiliates. All rights reserved.",
        "manufacturer": "Teleflex",
        "core_material": "Stainless steel",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.008\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating 17cm + polymer jacket 17cm",
        "tip_load": "0.8g",
        "radiopaque_length": "10cm",
        "available_lengths": "200, 300cm",
        "preferred_uses": "Specialty CTO Antegrade",
        "available_tip_styles": "Straight",
        "id": "16"
    },
    {
        "link_item": "Fielder FC",
        "model": "Fielder/Fielder FC",
        "image_url": require("../../../../assets/library_images/Asahi-12-FIELDER.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating over polymer jacket (20 cm)",
        "tip_load": "1g / 0.8g",
        "radiopaque_length": "3cm",
        "available_lengths": "180cm, 300cm",
        "preferred_uses": "Frontline finesse, Tortuous vessels, Side branch access",
        "available_tip_styles": "Straight, J-tip",
        "id": "17"
    },
    {
        "link_item": "Fielder XT-A",
        "model": "Fielder XT-A",
        "image_url": require("../../../../assets/library_images/Asahi-15-FIELDER-XT-A.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core [round core + twist wire]",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.010\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating over polymer jacket: 17cm",
        "tip_load": "1g",
        "radiopaque_length": "16cm",
        "available_lengths": "190, 300cm",
        "preferred_uses": "Specialty CTO Antegrade [Stumpless CTO crossing]",
        "available_tip_styles": "Straight",
        "id": "18"
    },
    {
        "link_item": "Fielder XT-R",
        "model": "Fielder XT-R",
        "image_url": require("../../../../assets/library_images/Asahi-16-FIELDER-XT-R.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core [round core + twist wire]",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.010\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating over polymer jacket: 17cm",
        "tip_load": "0.6g",
        "radiopaque_length": "16cm",
        "available_lengths": "190, 300cm",
        "preferred_uses": "Specialty CTO Retrograde, subtotal occlusions, long diffuse lesions",
        "available_tip_styles": "Straight",
        "id": "19"
    },
    {
        "link_item": "Fighter",
        "model": "Fighter",
        "image_url": require("../../../../assets/library_images/Boston-Scientific-19-FIGHTER.png"),
        "copyright_notice": "Image provided courtesy of Boston Scientific. © 2021 Boston Scientific Corporation or its affiliates. All rights reserved.",
        "manufacturer": "Boston Scientific",
        "core_material": "Stainless steel",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.009\"",
        "tip_design": "Core to tip",
        "tip_coating": "Clear polymer jacket and Hydrophilic coating",
        "tip_load": "1.5g",
        "radiopaque_length": "3.5cm",
        "available_lengths": "190, 300cm",
        "preferred_uses": "Specialty CTO Antegrade, subtotal occlusion, tortuous vessels",
        "available_tip_styles": "Straight",
        "id": "20"
    },
    {
        "link_item": "Hi-Torque Pilot 50",
        "model": "Pilot 50",
        "image_url": require("../../../../assets/library_images/Abbott-15-Pilot-50.png"),
        "copyright_notice": "Image provided courtesy of Abbott. © 2021 Abbott or its affiliates. All rights reserved.",
        "manufacturer": "Abbott",
        "core_material": "DURASTEEL",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip [Parabolic Core Grind]",
        "tip_coating": "Full Polymer cover with Hydrophilic coating",
        "tip_load": "1.5g",
        "radiopaque_length": "3cm",
        "available_lengths": "190, 300cm",
        "preferred_uses": "Specialty CTO Antegrade",
        "available_tip_styles": "Straight, J-tip",
        "id": "21"
    },
    {
        "link_item": "Hi-Torque Whisper ES",
        "model": "Whisper ES",
        "image_url": require("../../../../assets/library_images/Abbott-14-Whisper-ES.png"),
        "copyright_notice": "Image provided courtesy of Abbott. © 2021 Abbott or its affiliates. All rights reserved.",
        "manufacturer": "Abbott",
        "core_material": "DURASTEEL",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip [Parabolic Core Grind]",
        "tip_coating": "Full Polymer cover with Hydrophilic coating",
        "tip_load": "1.2g",
        "radiopaque_length": "3cm",
        "available_lengths": "190, 300cm",
        "preferred_uses": "Extra Support",
        "available_tip_styles": "Straight, J-tip",
        "id": "22"
    },
    {
        "link_item": "Raider",
        "model": "Raider",
        "image_url": require("../../../../assets/library_images/Teleflex-4-RAIDER.png"),
        "copyright_notice": "Image provided courtesy of Teleflex. © 2021 Teleflex or its affiliates. All rights reserved.",
        "manufacturer": "Teleflex",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating 30cm + polymer jacket 30cm",
        "tip_load": "4g",
        "radiopaque_length": "10cm",
        "available_lengths": "200, 300cm",
        "preferred_uses": "Specialty CTO Antegrade, subtotal occlusion, tortuous vessel",
        "available_tip_styles": "Straight",
        "id": "23"
    },
    {
        "link_item": "Sion Black",
        "model": "Sion Black",
        "image_url": require("../../../../assets/library_images/Asahi-4-BLACK.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core [round core + twist wire]",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "40cm hydrophilic coating + 20cm polymer jacket",
        "tip_load": "0.8g",
        "radiopaque_length": "3cm",
        "available_lengths": "190cm, 300cm",
        "preferred_uses": "Frontline finesse, tortuous vessels, Bifurcation, calcified lesions, Specialty CTO retrograde",
        "available_tip_styles": "Straight, J-Tip, Pre-shaped",
        "id": "24"
    },
    {
        "link_item": "Confianza Pro 9-12",
        "model": "Conquest/Confianza Pro 9 / 12",
        "image_url": require("../../../../assets/library_images/Asahi-34-CONFIANZA-Pro-12.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.009\"",
        "tip_design": "Core to tip",
        "tip_coating": "20cm hydrophilic coating (SLIP-COAT) on spring coil, non coated distal tip",
        "tip_load": "9g / 12g",
        "radiopaque_length": "20cm",
        "available_lengths": "180, 300cm",
        "preferred_uses": "Specialty CTO Antegrade [crossing heavily fibrous or calcified CTOs]",
        "available_tip_styles": "Straight",
        "id": "25"
    },
    {
        "link_item": "Fielder FC",
        "model": "Fielder/Fielder FC",
        "image_url": require("../../../../assets/library_images/Asahi-12-FIELDER.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating over polymer jacket (20 cm)",
        "tip_load": "1g / 0.8g",
        "radiopaque_length": "3cm",
        "available_lengths": "180cm, 300cm",
        "preferred_uses": "Frontline finesse, Tortuous vessels, Side branch access",
        "available_tip_styles": "Straight, J-Tip",
        "id": "26"
    },
    {
        "link_item": "Fielder XT-A",
        "model": "Fielder XT-A",
        "image_url": require("../../../../assets/library_images/Asahi-15-FIELDER-XT-A.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core [round core + twist wire]",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.010\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating over polymer jacket: 17cm",
        "tip_load": "1g",
        "radiopaque_length": "16cm",
        "available_lengths": "190, 300cm",
        "preferred_uses": "Specialty CTO Antegrade [Stumpless CTO crossing]",
        "available_tip_styles": "Straight",
        "id": "27"
    },
    {
        "link_item": "Fielder XT-R",
        "model": "Fielder XT-R",
        "image_url": require("../../../../assets/library_images/Asahi-16-FIELDER-XT-R.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core [round core + twist wire]",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.010\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating over polymer jacket: 17cm",
        "tip_load": "0.6g",
        "radiopaque_length": "16cm",
        "available_lengths": "190, 300cm",
        "preferred_uses": "Specialty CTO Retrograde, subtotal occlusions, long diffuse lesions",
        "available_tip_styles": "Straight",
        "id": "28"
    },
    {
        "link_item": "GAIA",
        "model": "Gaia First",
        "image_url": require("../../../../assets/library_images/Asahi-6-Gaia-First.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core [round core + twist wire]",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.010\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating 40cm with uncoated distal tip",
        "tip_load": "1.7g, tapered micro-cone",
        "radiopaque_length": "15cm",
        "available_lengths": "190, 300cm",
        "preferred_uses": "Specialty CTO Antegrade",
        "available_tip_styles": "Mini pre-shaped [1mm only]",
        "id": "29"
    },
    {
        "link_item": "GAIA Next",
        "model": "Gaia Next 1",
        "image_url": require("../../../../assets/library_images/Asahi-7-Gaia-Next-1.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core [round core + twist wire]",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.011\"",
        "tip_design": "Core to tip with XTRAND Coil",
        "tip_coating": "Hydrophilic coating 40cm with uncoated distal tip",
        "tip_load": "2g, tapered micro-cone",
        "radiopaque_length": "15cm",
        "available_lengths": "190cm",
        "preferred_uses": "Specialty CTO Antegrade",
        "available_tip_styles": "Pre-shaped [1mm only]",
        "id": "30"
    },
    {
        "link_item": "Gladius Mongo",
        "model": "Gladius Mongo",
        "image_url": require("../../../../assets/library_images/Asahi-17-GLADIUS-MONGO.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core [round core + twist wire]",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating (41cm) over polymer jacket (SLIP-COAT)",
        "tip_load": "3g",
        "radiopaque_length": "3cm",
        "available_lengths": "190, 300cm",
        "preferred_uses": "Specialty CTO Antegrade and Retrograde, long lesions",
        "available_tip_styles": "Straight, Pre-shaped",
        "id": "31"
    },
    {
        "link_item": "Hi-Torque Cross-IT 100 XT",
        "model": "CROSS-IT 100XT",
        "image_url": require("../../../../assets/library_images/Abbott-28-Cross-It-100XT.png"),
        "copyright_notice": "Image provided courtesy of Abbott. © 2021 Abbott or its affiliates. All rights reserved.",
        "manufacturer": "Abbott",
        "core_material": "Stainless Steel",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.010\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hyrdrophilic",
        "tip_load": "1.7g",
        "radiopaque_length": "3cm",
        "available_lengths": "190, 300cm",
        "preferred_uses": "Specialty CTO Antegrade",
        "available_tip_styles": "Straight, J shaped",
        "id": "32"
    },
    {
        "link_item": "Hi-Torque Pilot 150, 200",
        "model": "Pilot 150 / 200",
        "image_url": require("../../../../assets/library_images/Abbott-16-Pilot-150.png"),
        "copyright_notice": "Image provided courtesy of Abbott. © 2021 Abbott or its affiliates. All rights reserved.",
        "manufacturer": "Abbott",
        "core_material": "DURASTEEL",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip [Parabolic Core Grind]",
        "tip_coating": "Full Polymer cover with Hydrophilic coating",
        "tip_load": "2.7g / 4.1g",
        "radiopaque_length": "3cm",
        "available_lengths": "190, 300cm",
        "preferred_uses": "Specialty CTO Antegrade",
        "available_tip_styles": "Straight, J-tip",
        "id": "33"
    },
    {
        "link_item": "Hi-Torque Progress 40",
        "model": "PROGRESS 40",
        "image_url": require("../../../../assets/library_images/Abbott-23-Progress-40.png"),
        "copyright_notice": "Image provided courtesy of Abbott. © 2021 Abbott or its affiliates. All rights reserved.",
        "manufacturer": "Abbott",
        "core_material": "DURASTEEL",
        "core_tapering": "No",
        "diameter": "0.012\"",
        "tip_design": "Core to tip [Parabolic Core Grind]",
        "tip_coating": "Hydrophilic [Intermediate Polymer Sleeve, distal 3cm uncoated]",
        "tip_load": "4.8g",
        "radiopaque_length": "3cm",
        "available_lengths": "190, 300cm",
        "preferred_uses": "Specialty CTO Antegrade",
        "available_tip_styles": "Straight",
        "id": "34"
    },
    {
        "link_item": "Hi-Torque Progress 200",
        "model": "PROGRESS 200T",
        "image_url": require("../../../../assets/library_images/Abbott-27-Progress-200T.png"),
        "copyright_notice": "Image provided courtesy of Abbott. © 2021 Abbott or its affiliates. All rights reserved.",
        "manufacturer": "Abbott",
        "core_material": "DURASTEEL",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.009\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic [Intermediate Polymer Sleeve, distal 3cm uncoated]",
        "tip_load": "13g",
        "radiopaque_length": "3cm",
        "available_lengths": "190, 300cm",
        "preferred_uses": "Specialty CTO Antegrade",
        "available_tip_styles": "Straight",
        "id": "35"
    },
    {
        "link_item": "Hornet 10, 14",
        "model": "Hornet 10 / 14",
        "image_url": require("../../../../assets/library_images/Boston-Scientific-23-HORNET-10.png"),
        "copyright_notice": "Image provided courtesy of Boston Scientific. © 2021 Boston Scientific or its affiliates. All rights reserved.",
        "manufacturer": "Boston Scientific",
        "core_material": "Stainless steel",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.008\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic",
        "tip_load": "10g / 14g",
        "radiopaque_length": "3.5cm",
        "available_lengths": "190, 300cm",
        "preferred_uses": "Specialty CTO Antegrade",
        "available_tip_styles": "Straight",
        "id": "36"
    },
    {
        "link_item": "MiracleBros 3-12",
        "model": "Miraclebros 3 / 4.5 / 6 / 12",
        "image_url": require("../../../../assets/library_images/Asahi-28-MIRACLEbros-3.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "11cm hydrophobic coating",
        "tip_load": "3g / 4.5g / 6g / 12g",
        "radiopaque_length": "11cm",
        "available_lengths": "180, 300cm",
        "preferred_uses": "Specialty CTO Antegrade [controlled CTO drilling]",
        "available_tip_styles": "Straight",
        "id": "37"
    },
    {
        "link_item": "RG3",
        "model": "RG3",
        "image_url": require("../../../../assets/library_images/Asahi-36-RG3.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.010\"",
        "tip_design": "Core to tip",
        "tip_coating": "170cm distal hydrophilic coating, 160cm proximal hydrophobic coating",
        "tip_load": "3g",
        "radiopaque_length": "3cm",
        "available_lengths": "330cm",
        "preferred_uses": "Specialty CTO Retrograde [guide wire externalization only]",
        "available_tip_styles": "Straight",
        "id": "38"
    },
    {
        "link_item": "R350",
        "model": "R350",
        "image_url": require("../../../../assets/library_images/Teleflex-1-R350.png"),
        "copyright_notice": "Image provided courtesy of Teleflex. © 2021 Teleflex or its affiliates. All rights reserved.",
        "manufacturer": "Teleflex",
        "core_material": "Nitinol",
        "core_tapering": "No",
        "diameter": "0.013\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating on distal 200cm",
        "tip_load": "3g",
        "radiopaque_length": "5cm",
        "available_lengths": "350cm",
        "preferred_uses": "Specialty CTO retrograde channels, tortuous vessels [softest tip]",
        "available_tip_styles": "Straight",
        "id": "39"
    },
    {
        "link_item": "Sion",
        "model": "Sion",
        "image_url": require("../../../../assets/library_images/Asahi-1-SION.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core [round core + twist wire]",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "Full hydrophilic coating (SLIP-COAT)",
        "tip_load": "0.7g",
        "radiopaque_length": "3cm",
        "available_lengths": "180, 300cm",
        "preferred_uses": "Workhorse wire, tortuous vessels and side branches",
        "available_tip_styles": "Straight, J-Tip",
        "id": "40"
    },
    {
        "link_item": "Sion Black",
        "model": "Sion Black",
        "image_url": require("../../../../assets/library_images/Asahi-4-BLACK.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core [round core + twist wire]",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "40cm hydrophilic coating + 20cm polymer jacket",
        "tip_load": "0.8g",
        "radiopaque_length": "3cm",
        "available_lengths": "190, 300cm",
        "preferred_uses": "Frontline finesse, tortuous vessels, Bifurcation, calcified lesions, Specialty CTO retrograde",
        "available_tip_styles": "Straight, J-Tip, Pre-shaped",
        "id": "41"
    }
];
