export const retrogradeRoutes = [
    {
        "id": "1",
        "link_item": "Fielder, Fielder FC",
        "model": "Fielder/Fielder FC",
        "image_url": require("../../../../../assets/library_images/Asahi-12-FIELDER.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating over polymer jacket (20 cm)",
        "tip_load": "1g / 0.8g",
        "radiopaque_length": "3cm",
        "available_lengths": "180, 300cm",
        "available_tip_styles": "Straight, J-tip",
        "preferred_uses": "Frontline finesse, Tortuous vessels, Side branch access"
    },
    {
        "id": "2",
        "link_item": "Fielder XT-R",
        "model": "Fielder XT-R",
        "image_url": require("../../../../../assets/library_images/Asahi-16-FIELDER-XT-R.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core [round core + twist wire]",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.010\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating over polymer jacket: 17cm",
        "tip_load": "0.6g",
        "radiopaque_length": "16cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Specialty CTO Retrograde, subtotal occlusions, long diffuse lesions"
    },
    {
        "id": "3",
        "link_item": "Sion Black",
        "model": "Sion Black",
        "image_url": require("../../../../../assets/library_images/Asahi-4-BLACK.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core [round core + twist wire]",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "40cm hydrophilic coating + 20cm polymer jacket",
        "tip_load": "0.8g",
        "radiopaque_length": "3cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Straight, J-Tip, Pre-shaped",
        "preferred_uses": "Frontline finesse, tortuous vessels, Bifurcation, calcified lesions, Specialty CTO retrograde"
    },
    {
        "id": "4",
        "link_item": "Suoh 03",
        "model": "Suoh 03",
        "image_url": require("../../../../../assets/library_images/Asahi-37-SUOH-03.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core with shaping wire to tip, proprietary extra coil and wire tech",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Shaping ribbon",
        "tip_coating": "Hydrophilic coating over distal 52cm [SLIP COAT]",
        "tip_load": "0.3g",
        "radiopaque_length": "3cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Straight, Pre-shaped",
        "preferred_uses": "Specialty CTO retrograde channels, septal navigation/surfing, tortuous vessels [softest tip]"
    },
    {
        "id": "5",
        "link_item": "Gaia",
        "model": "Gaia First",
        "image_url": require("../../../../../assets/library_images/Asahi-6-Gaia-First.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core [round core + twist wire]",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.010\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating 40cm with uncoated distal tip",
        "tip_load": "1.7g, tapered micro-cone",
        "radiopaque_length": "15cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Mini pre-shaped [1mm only]",
        "preferred_uses": "Specialty CTO Antegrade"
    },
    {
        "id": "6",
        "link_item": "Gaia Next",
        "model": "Gaia Next 1",
        "image_url": require("../../../../../assets/library_images/Asahi-7-Gaia-Next-1.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core [round core + twist wire]",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.011\"",
        "tip_design": "Core to tip with XTRAND Coil",
        "tip_coating": "Hydrophilic coating 40cm with uncoated distal tip",
        "tip_load": "2g, tapered micro-cone",
        "radiopaque_length": "15cm",
        "available_lengths": "190cm",
        "available_tip_styles": "Pre-shaped [1mm only]",
        "preferred_uses": "Specialty CTO Antegrade"
    },
    {
        "id": "7",
        "link_item": "MiracleBros",
        "model": "Miraclebros 3 / 4.5 / 6 / 12",
        "image_url": require("../../../../../assets/library_images/Asahi-28-MIRACLEbros-3.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "11cm hydrophobic coating",
        "tip_load": "3g / 4.5g / 6g / 12g",
        "radiopaque_length": "11cm",
        "available_lengths": "180, 300cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Specialty CTO Antegrade [controlled CTO drilling]"
    },
    {
        "id": "8",
        "link_item": "Confianza Pro",
        "model": "Conquest/Confianza Pro",
        "image_url": require("../../../../../assets/library_images/Asahi-33-CONFIANZA-Pro-9.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.009\"",
        "tip_design": "Core to tip",
        "tip_coating": "20cm hydrophilic coating (SLIP-COAT) on spring coil, non coated distal tip",
        "tip_load": "9g",
        "radiopaque_length": "20cm",
        "available_lengths": "180, 300cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Specialty CTO Antegrade [crossing heavily fibrous or calcified CTOs]"
    },
    {
        "id": "9",
        "link_item": "RG3",
        "model": "RG3",
        "image_url": require("../../../../../assets/library_images/Asahi-36-RG3.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.010\"",
        "tip_design": "Core to tip",
        "tip_coating": "170cm distal hydrophilic coating, 160cm proximal hydrophobic coating",
        "tip_load": "3g",
        "radiopaque_length": "3cm",
        "available_lengths": "330cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Specialty CTO Retrograde [guide wire externalization only]"
    },
    {
        "id": "10",
        "link_item": "R350",
        "model": "R350",
        "image_url": require("../../../../../assets/library_images/Teleflex-1-R350.png"),
        "copyright_notice": "Image provided courtesy of Teleflex. © 2021 Teleflex or its affiliates. All rights reserved.",
        "manufacturer": "Teleflex",
        "core_material": "Nitinol",
        "core_tapering": "No",
        "diameter": "0.013\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating on distal 200cm",
        "tip_load": "3g",
        "radiopaque_length": "5cm",
        "available_lengths": "350cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Specialty CTO retrograde channels, tortuous vessels [softest tip]"
    },
    {
        "id": "11",
        "link_item": "Viperwire Advance",
        "model": "Viperwire Advance",
        "image_url": require("../../../../../assets/library_images/Cardiovascular-Systems-Inc-1-Viperwire-Advance.png"),
        "copyright_notice": "Image provided courtesy of Cardiovascular Systems Inc. © 2021 Cardiovascular Systems Inc. or its affiliates. All rights reserved.",
        "manufacturer": "Cardiovascular Systems Inc.",
        "core_material": "304V Stainless steel",
        "core_tapering": "Yes",
        "diameter": "0.012\" core diameter with tip diameter of 0.014\"",
        "tip_design": "Core to tip, Platinum/Tungsten",
        "tip_coating": "Hydrophobic silicone coating",
        "tip_load": "1.4g at 10mm",
        "radiopaque_length": "2.5cm",
        "available_lengths": "335cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Orbital Atherectomy"
    }
];

export const antogradeRoutes = [
    {
        "id": "1",
        "link_item": "Fielder",
        "model": "Fielder/Fielder FC",
        "image_url": require("../../../../../assets/library_images/Asahi-12-FIELDER.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating over polymer jacket (20 cm)",
        "tip_load": "1g / 0.8g",
        "radiopaque_length": "3cm",
        "available_lengths": "180, 300cm",
        "available_tip_styles": "Straight, J-tip",
        "preferred_uses": "Frontline finesse, Tortuous vessels, Side branch access"
    },
    {
        "id": "2",
        "link_item": "Fielder XT",
        "model": "Fielder XT",
        "image_url": require("../../../../../assets/library_images/Asahi-14-FIELDER-XT.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core [round core + twist wire]",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.009\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating over polymer jacket: 16cm",
        "tip_load": "0.8g, tapered micro-cone",
        "radiopaque_length": "16cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Straight, J-tip",
        "preferred_uses": "Specialty CTO Antegrade, subtotal occlusion"
    },
    {
        "id": "3",
        "link_item": "Fielder XT-A",
        "model": "Fielder XT-A",
        "image_url": require("../../../../../assets/library_images/Asahi-15-FIELDER-XT-A.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core [round core + twist wire]",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.010\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating over polymer jacket: 17cm",
        "tip_load": "1g",
        "radiopaque_length": "16cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Specialty CTO Antegrade [Stumpless CTO crossing]"
    },
    {
        "id": "4",
        "link_item": "Fielder XT-R",
        "model": "Fielder XT-R",
        "image_url": require("../../../../../assets/library_images/Asahi-16-FIELDER-XT-R.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core [round core + twist wire]",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.010\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating over polymer jacket: 17cm",
        "tip_load": "0.6g",
        "radiopaque_length": "16cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Specialty CTO Retrograde, subtotal occlusions, long diffuse lesions"
    },
    {
        "id": "5",
        "link_item": "MiracleBros",
        "model": "Miraclebros 3 / 4.5 / 6 / 12",
        "image_url": require("../../../../../assets/library_images/Asahi-28-MIRACLEbros-3.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "11cm hydrophobic coating",
        "tip_load": "3g / 4.5g / 6g / 12g",
        "radiopaque_length": "11cm",
        "available_lengths": "180, 300cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Specialty CTO Antegrade [controlled CTO drilling]"
    },
    {
        "id": "6",
        "link_item": "Gaia 3",
        "model": "Gaia Third",
        "image_url": require("../../../../../assets/library_images/Asahi-10-Gaia-Third.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core [round core + twist wire]",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.012\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating 40cm with uncoated distal tip",
        "tip_load": "4.5g, tapered micro-cone",
        "radiopaque_length": "15cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Mini pre-shaped [1mm only]",
        "preferred_uses": "Specialty CTO Antegrade [hard tissue and fibrous cap]"
    },
    {
        "id": "7",
        "link_item": "Confianza 9/12",
        "model": "Conquest/Confianza Pro 9 / 12",
        "image_url": require("../../../../../assets/library_images/Asahi-34-CONFIANZA-Pro-12.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.009\"",
        "tip_design": "Core to tip",
        "tip_coating": "20cm hydrophilic coating (SLIP-COAT) on spring coil, non coated distal tip",
        "tip_load": "9g / 12g",
        "radiopaque_length": "20cm",
        "available_lengths": "180, 300cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Specialty CTO Antegrade [crossing heavily fibrous or calcified CTOs]"
    },
    {
        "id": "8",
        "link_item": "Fielder",
        "model": "Fielder/Fielder FC",
        "image_url": require("../../../../../assets/library_images/Asahi-12-FIELDER.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating over polymer jacket (20 cm)",
        "tip_load": "1g / 0.8g",
        "radiopaque_length": "3cm",
        "available_lengths": "180, 300cm",
        "available_tip_styles": "Straight, J-tip",
        "preferred_uses": "Frontline finesse, Tortuous vessels, Side branch access"
    },
    {
        "id": "9",
        "link_item": "Fielder XT",
        "model": "Fielder XT",
        "image_url": require("../../../../../assets/library_images/Asahi-14-FIELDER-XT.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core [round core + twist wire]",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.009\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating over polymer jacket: 16cm",
        "tip_load": "0.8g, tapered micro-cone",
        "radiopaque_length": "16cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Straight, J-tip",
        "preferred_uses": "Specialty CTO Antegrade, subtotal occlusion"
    },
    {
        "id": "10",
        "link_item": "Fielder XT-A",
        "model": "Fielder XT-A",
        "image_url": require("../../../../../assets/library_images/Asahi-15-FIELDER-XT-A.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core [round core + twist wire]",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.010\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating over polymer jacket: 17cm",
        "tip_load": "1g",
        "radiopaque_length": "16cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Specialty CTO Antegrade [Stumpless CTO crossing]"
    },
    {
        "id": "11",
        "link_item": "Gaia 1",
        "model": "Gaia First",
        "image_url": require("../../../../../assets/library_images/Asahi-6-Gaia-First.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core [round core + twist wire]",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.010\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating 40cm with uncoated distal tip",
        "tip_load": "1.7g, tapered micro-cone",
        "radiopaque_length": "15cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Mini pre-shaped [1mm only]",
        "preferred_uses": "Specialty CTO Antegrade"
    },
    {
        "id": "12",
        "link_item": "Gaia 2",
        "model": "Gaia Second",
        "image_url": require("../../../../../assets/library_images/Asahi-8-Gaia-Second.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core [round core + twist wire]",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.011\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating 40cm with uncoated distal tip",
        "tip_load": "3.5g, tapered micro-cone",
        "radiopaque_length": "15cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Mini pre-shaped [1mm only]",
        "preferred_uses": "Specialty CTO Antegrade [hard tissue and fibrous cap]"
    },
    {
        "id": "13",
        "link_item": "High torque Pilot 50",
        "model": "Pilot 50",
        "image_url": require("../../../../../assets/library_images/Abbott-15-Pilot-50.png"),
        "copyright_notice": "Image provided courtesy of Abbott. © 2021 Abbott or its affiliates. All rights reserved.",
        "manufacturer": "Abbott",
        "core_material": "DURASTEEL",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip [Parabolic Core Grind]",
        "tip_coating": "Full Polymer cover with Hydrophilic coating",
        "tip_load": "1.5g",
        "radiopaque_length": "3cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Straight, J-tip",
        "preferred_uses": "Specialty CTO Antegrade"
    },
    {
        "id": "14",
        "link_item": "High torque Pilot 150",
        "model": "Pilot 150 / 200",
        "image_url": require("../../../../../assets/library_images/Abbott-16-Pilot-150.png"),
        "copyright_notice": "Image provided courtesy of Abbott. © 2021 Abbott or its affiliates. All rights reserved.",
        "manufacturer": "Abbott",
        "core_material": "DURASTEEL",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip [Parabolic Core Grind]",
        "tip_coating": "Full Polymer cover with Hydrophilic coating",
        "tip_load": "2.7g / 4.1g",
        "radiopaque_length": "3cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Straight, J-tip",
        "preferred_uses": "Specialty CTO Antegrade"
    },
    {
        "id": "15",
        "link_item": "Fielder",
        "model": "Fielder/Fielder FC",
        "image_url": require("../../../../../assets/library_images/Asahi-12-FIELDER.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating over polymer jacket (20 cm)",
        "tip_load": "1g / 0.8g",
        "radiopaque_length": "3cm",
        "available_lengths": "180, 300cm",
        "available_tip_styles": "Straight, J-tip",
        "preferred_uses": "Frontline finesse, Tortuous vessels, Side branch access"
    },
    {
        "id": "16",
        "link_item": "Fielder XT",
        "model": "Fielder XT",
        "image_url": require("../../../../../assets/library_images/Asahi-14-FIELDER-XT.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core [round core + twist wire]",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.009\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating over polymer jacket: 16cm",
        "tip_load": "0.8g, tapered micro-cone",
        "radiopaque_length": "16cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Straight, J-tip",
        "preferred_uses": "Specialty CTO Antegrade, subtotal occlusion"
    },
    {
        "id": "17",
        "link_item": "Fielder XT-A",
        "model": "Fielder XT-A",
        "image_url": require("../../../../../assets/library_images/Asahi-15-FIELDER-XT-A.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core [round core + twist wire]",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.010\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating over polymer jacket: 17cm",
        "tip_load": "1g",
        "radiopaque_length": "16cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Specialty CTO Antegrade [Stumpless CTO crossing]"
    },
    {
        "id": "18",
        "link_item": "Fielder XT-R",
        "model": "Fielder XT-R",
        "image_url": require("../../../../../assets/library_images/Asahi-16-FIELDER-XT-R.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core [round core + twist wire]",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.010\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating over polymer jacket: 17cm",
        "tip_load": "0.6g",
        "radiopaque_length": "16cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Specialty CTO Retrograde, subtotal occlusions, long diffuse lesions"
    },
    {
        "id": "19",
        "link_item": "Gaia 2",
        "model": "Gaia Second",
        "image_url": require("../../../../../assets/library_images/Asahi-8-Gaia-Second.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core [round core + twist wire]",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.011\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating 40cm with uncoated distal tip",
        "tip_load": "3.5g, tapered micro-cone",
        "radiopaque_length": "15cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Mini pre-shaped [1mm only]",
        "preferred_uses": "Specialty CTO Antegrade [hard tissue and fibrous cap]"
    },
    {
        "id": "20",
        "link_item": "Gaia 3",
        "model": "Gaia Third",
        "image_url": require("../../../../../assets/library_images/Asahi-10-Gaia-Third.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core [round core + twist wire]",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.012\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating 40cm with uncoated distal tip",
        "tip_load": "4.5g, tapered micro-cone",
        "radiopaque_length": "15cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Mini pre-shaped [1mm only]",
        "preferred_uses": "Specialty CTO Antegrade [hard tissue and fibrous cap]"
    },
    {
        "id": "21",
        "link_item": "MiracleBros 3, 4.5, 6",
        "model": "Miraclebros 3 / 4.5 / 6",
        "image_url": require("../../../../../assets/library_images/Asahi-28-MIRACLEbros-3.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "11cm hydrophobic coating",
        "tip_load": "3g / 4.5g / 6g",
        "radiopaque_length": "11cm",
        "available_lengths": "180, 300cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Specialty CTO Antegrade [controlled CTO drilling]"
    },
    {
        "id": "22",
        "link_item": "Confianza Pro",
        "model": "Conquest/Confianza Pro",
        "image_url": require("../../../../../assets/library_images/Asahi-33-CONFIANZA-Pro-9.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.009\"",
        "tip_design": "Core to tip",
        "tip_coating": "20cm hydrophilic coating (SLIP-COAT) on spring coil, non coated distal tip",
        "tip_load": "9g",
        "radiopaque_length": "20cm",
        "available_lengths": "180, 300cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Specialty CTO Antegrade [crossing heavily fibrous or calcified CTOs]"
    },
    {
        "id": "23",
        "link_item": "MiracleBros 6, 12",
        "model": "Miraclebros 6 / 12",
        "image_url": require("../../../../../assets/library_images/Asahi-28-MIRACLEbros-3.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "11cm hydrophobic coating",
        "tip_load": "6g / 12g",
        "radiopaque_length": "11cm",
        "available_lengths": "180, 300cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Specialty CTO Antegrade [controlled CTO drilling]"
    },
    {
        "id": "24",
        "link_item": "Confianza Pro 9, 12",
        "model": "Conquest/Confianza Pro 9 / 12",
        "image_url": require("../../../../../assets/library_images/Asahi-34-CONFIANZA-Pro-12.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.009\"",
        "tip_design": "Core to tip",
        "tip_coating": "20cm hydrophilic coating (SLIP-COAT) on spring coil, non coated distal tip",
        "tip_load": "9g / 12g",
        "radiopaque_length": "20cm",
        "available_lengths": "180, 300cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Specialty CTO Antegrade [crossing heavily fibrous or calcified CTOs]"
    },
    {
        "id": "25",
        "link_item": "Pilot 200",
        "model": "Pilot 200",
        "image_url": require("../../../../../assets/library_images/Abbott-16-Pilot-150.png"),
        "copyright_notice": "Image provided courtesy of Abbott. © 2021 Abbott or its affiliates. All rights reserved.",
        "manufacturer": "Abbott",
        "core_material": "DURASTEEL",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip [Parabolic Core Grind]",
        "tip_coating": "Full Polymer cover with Hydrophilic coating",
        "tip_load": "4.1g",
        "radiopaque_length": "3cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Straight, J-tip",
        "preferred_uses": "Specialty CTO Antegrade"
    },
    {
        "id": "26",
        "link_item": "Progress 200T",
        "model": "PROGRESS 200T",
        "image_url": require("../../../../../assets/library_images/Abbott-27-Progress-200T.png"),
        "copyright_notice": "Image provided courtesy of Abbott. © 2021 Abbott or its affiliates. All rights reserved.",
        "manufacturer": "Abbott",
        "core_material": "DURASTEEL",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.009\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic [Intermediate Polymer Sleeve, distal 3cm uncoated]",
        "tip_load": "13g",
        "radiopaque_length": "3cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Specialty CTO Antegrade"
    },
    {
        "id": "27",
        "link_item": "Pilot 200",
        "model": "Pilot 200",
        "image_url": require("../../../../../assets/library_images/Asahi-8-Gaia-Second.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core [round core + twist wire]",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.011\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating 40cm with uncoated distal tip",
        "tip_load": "3.5g, tapered micro-cone",
        "radiopaque_length": "15cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Mini pre-shaped [1mm only]",
        "preferred_uses": "Specialty CTO Antegrade [hard tissue and fibrous cap]"
    },
    {
        "id": "28",
        "link_item": "Confianza Pro",
        "model": "Conquest/Confianza Pro",
        "image_url": require("../../../../../assets/library_images/Asahi-33-CONFIANZA-Pro-9.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.009\"",
        "tip_design": "Core to tip",
        "tip_coating": "20cm hydrophilic coating (SLIP-COAT) on spring coil, non coated distal tip",
        "tip_load": "9g",
        "radiopaque_length": "20cm",
        "available_lengths": "180, 300cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Specialty CTO Antegrade [crossing heavily fibrous or calcified CTOs]"
    },
    {
        "id": "29",
        "link_item": "Hornet 10, 14",
        "model": "Hornet 10 / 14",
        "image_url": require("../../../../../assets/library_images/Boston-Scientific-23-HORNET-10.png"),
        "copyright_notice": "Image provided courtesy of Boston Scientific. © 2021 Boston Scientific or its affiliates. All rights reserved.",
        "manufacturer": "Boston Scientific",
        "core_material": "Stainless steel",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.008\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic",
        "tip_load": "10g / 14g",
        "radiopaque_length": "3.5cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Specialty CTO Antegrade"
    },
    {
        "id": "30",
        "link_item": "Gaia",
        "model": "Gaia First",
        "image_url": require("../../../../../assets/library_images/Asahi-6-Gaia-First.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core [round core + twist wire]",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.010\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating 40cm with uncoated distal tip",
        "tip_load": "1.7g, tapered micro-cone",
        "radiopaque_length": "15cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Mini pre-shaped [1mm only]",
        "preferred_uses": "Specialty CTO Antegrade"
    },
    {
        "id": "31",
        "link_item": "Gaia Next Series",
        "model": "Gaia Next 1",
        "image_url": require("../../../../../assets/library_images/Asahi-7-Gaia-Next-1.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel composite core [round core + twist wire]",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.011\"",
        "tip_design": "Core to tip with XTRAND Coil",
        "tip_coating": "Hydrophilic coating 40cm with uncoated distal tip",
        "tip_load": "2g, tapered micro-cone",
        "radiopaque_length": "15cm",
        "available_lengths": "190cm",
        "available_tip_styles": "Pre-shaped [1mm only]",
        "preferred_uses": "Specialty CTO Antegrade"
    },
    {
        "id": "32",
        "link_item": "MiracleBros 4.5, 6",
        "model": "Miraclebros 4.5 / 6",
        "image_url": require("../../../../../assets/library_images/Asahi-28-MIRACLEbros-3.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "11cm hydrophobic coating",
        "tip_load": "4.5g / 6g",
        "radiopaque_length": "11cm",
        "available_lengths": "180, 300cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Specialty CTO Antegrade [controlled CTO drilling]"
    },
    {
        "id": "33",
        "link_item": "Confianza Pro",
        "model": "Conquest/Confianza Pro",
        "image_url": require("../../../../../assets/library_images/Asahi-33-CONFIANZA-Pro-9.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.009\"",
        "tip_design": "Core to tip",
        "tip_coating": "20cm hydrophilic coating (SLIP-COAT) on spring coil, non coated distal tip",
        "tip_load": "9g",
        "radiopaque_length": "20cm",
        "available_lengths": "180, 300cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Specialty CTO Antegrade [crossing heavily fibrous or calcified CTOs]"
    },
    {
        "id": "34",
        "link_item": "Ultimatebros 3",
        "model": "Ultimatebros 3",
        "image_url": require("../../../../../assets/library_images/Asahi-27-ULTIMATEbros-3.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless Steel",
        "core_tapering": "No",
        "diameter": "0.014\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating (40cm) with uncoated distal tip (hydrophobic)",
        "tip_load": "3g",
        "radiopaque_length": "11cm",
        "available_lengths": "180, 300cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Specialty CTO Antegrade [Controlled CTO drilling]"
    },
    {
        "id": "35",
        "link_item": "Progress 140T",
        "model": "PROGRESS 140T",
        "image_url": require("../../../../../assets/library_images/Abbott-26-Progress-140T.png"),
        "copyright_notice": "Image provided courtesy of Abbott. © 2021 Abbott or its affiliates. All rights reserved.",
        "manufacturer": "Abbott",
        "core_material": "DURASTEEL",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.0105\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic [Intermediate Polymer Sleeve, distal 3cm uncoated]",
        "tip_load": "12.5g",
        "radiopaque_length": "3cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Specialty CTO Antegrade"
    },
    {
        "id": "36",
        "link_item": "Progress 200T",
        "model": "PROGRESS 200T",
        "image_url": require("../../../../../assets/library_images/Abbott-27-Progress-200T.png"),
        "copyright_notice": "Image provided courtesy of Abbott. © 2021 Abbott or its affiliates. All rights reserved.",
        "manufacturer": "Abbott",
        "core_material": "DURASTEEL",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.009\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic [Intermediate Polymer Sleeve, distal 3cm uncoated]",
        "tip_load": "13g",
        "radiopaque_length": "3cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Specialty CTO Antegrade"
    },
    {
        "id": "37",
        "link_item": "Confianza Pro 12",
        "model": "Conquest/Confianza Pro 12",
        "image_url": require("../../../../../assets/library_images/Asahi-34-CONFIANZA-Pro-12.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.009\"",
        "tip_design": "Core to tip",
        "tip_coating": "20cm hydrophilic coating (SLIP-COAT) on spring coil, non coated distal tip",
        "tip_load": "12g",
        "radiopaque_length": "20cm",
        "available_lengths": "180, 300cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Specialty CTO Antegrade [crossing heavily fibrous or calcified CTOs]"
    },
    {
        "id": "38",
        "link_item": "Progress 200T",
        "model": "PROGRESS 200T",
        "image_url": require("../../../../../assets/library_images/Abbott-27-Progress-200T.png"),
        "copyright_notice": "Image provided courtesy of Abbott. © 2021 Abbott or its affiliates. All rights reserved.",
        "manufacturer": "Abbott",
        "core_material": "DURASTEEL",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.009\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic [Intermediate Polymer Sleeve, distal 3cm uncoated]",
        "tip_load": "13g",
        "radiopaque_length": "3cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Specialty CTO Antegrade"
    },
    {
        "id": "39",
        "link_item": "Hornet 14",
        "model": "Hornet 14",
        "image_url": require("../../../../../assets/library_images/Boston-Scientific-23-HORNET-10.png"),
        "copyright_notice": "Image provided courtesy of Boston Scientific. © 2021 Boston Scientific or its affiliates. All rights reserved.",
        "manufacturer": "Boston Scientific",
        "core_material": "Stainless steel",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.008\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic",
        "tip_load": "14g",
        "radiopaque_length": "3.5cm",
        "available_lengths": "190, 300cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Specialty CTO Antegrade"
    },
    {
        "id": "40",
        "link_item": "Astato 20",
        "model": "ASTATO XS 20",
        "image_url": require("../../../../../assets/library_images/Asahi-19-Astato-XS-20.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.008\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating with uncoated distal tip (SLIP-COAT)",
        "tip_load": "20g",
        "radiopaque_length": "17cm",
        "available_lengths": "180, 300cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Specialty CTO Antegrade and Retrograde, Thick and heavily calcified caps"
    },
    {
        "id": "41",
        "link_item": "Astato 40",
        "model": "ASTATO XS 40",
        "image_url": require("../../../../../assets/library_images/Asahi-20-Astato-XS-40.png"),
        "copyright_notice": "Image provided courtesy of Asahi Intecc. © 2021 Asahi Intecc or its affiliates. All rights reserved.",
        "manufacturer": "Asahi Intecc",
        "core_material": "Stainless steel",
        "core_tapering": "Yes",
        "diameter": "0.014\" -> 0.009\"",
        "tip_design": "Core to tip",
        "tip_coating": "Hydrophilic coating with uncoated distal tip (SLIP-COAT)",
        "tip_load": "40g (Highest tip load for maximum penetration)",
        "radiopaque_length": "17cm",
        "available_lengths": "180, 300cm",
        "available_tip_styles": "Straight",
        "preferred_uses": "Specialty CTO Antegrade and Retrograde, Thick and heavily calcified caps"
    }
];